print("Hello, World!")
print("Hello, Lua!")
print("Hello, Python!")
print("Hello, Java!")
print("Hello, C++!")
print("Hello, C#!")
print("Hello, JavaScript!")
print("Hello, TypeScript!")
print("Hello, Go!")
print("Hello, Rust!")
print("Hello, Kotlin!")
print("Hello, Swift!")
print("Hello, Dart!")
print("Goodbye!")
